version: 0.2

env:
  variables:
    JDBC_DRIVER: $(aws ssm get-parameter --name "/my-app/JDBC_DRIVER" --with-decryption --query "Parameter.Value" --output text)
    DATASOURCE_URL: $(aws ssm get-parameter --name "/my-app/DATASOURCE_URL" --query "Parameter.Value" --output text)
    DATASOURCE_USER: $(aws ssm get-parameter --name "/my-app/DATASOURCE_USER" --with-decryption --query "Parameter.Value" --output text)
    DATASOURCE_PASSWORD: $(aws ssm get-parameter --name "/my-app/DATASOURCE_PASSWORD" --with-decryption --query "Parameter.Value" --output text)

   
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y python3 python3-pip
      - pip install awscli
      - echo "Installing AWS IAM Authenticator..."
      - curl -o aws-iam-authenticator https://s3.us-east-1.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      - echo "AWS CLI installed successfully!"
      - echo "Listing S3 buckets..."
      - aws s3 ls
      - aws --version
      - echo "Installing Terraform..."
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt-get update && sudo apt-get install -y terraform
      - terraform -v
      - echo "Configuring AWS CLI..."
    
      
  pre_build:
    commands:
      - echo "Running Terraform init..."
      - terraform init

  build:
    commands:
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Deployment completed successfully!"
      - echo "You can check your Elastic Beanstalk environment in the AWS Management Console."

# artifacts:
#  files:
#    - terraform/** 
